### ISSUE TITLE
Why remove registrationId?

### ISSUE THREAD

**Issue by crossle** [christophhagen/LibSignalProtocolSwift#5]

**Comment by christophhagen** [comment]
I removed the registrationId because it's not needed. The protocol works fine without it, I don't even know why it's included in the `libsignal-protocol-c` library, as it's never used in the code for anything.

**Comment by crossle** [comment]
OK, I already found it not used

**Comment by guarland** [comment]
@christophhagen  registrationId is very important in signal protocol, if you look at the signal server code, make sure of this, with the help of this you can find out that the second end uses the new keys so it's reinstalled the program, so that it reinstalled the program

Great thanks for this library, works like a Swiss watch : )
